# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# For more details on how to configure your build environment visit
# http://www.gradle.org/configure-build-environment

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for headless machines. See also http://gradle.org/daemon
# Increase this value if you want the daemon process to use more memory.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/configure-build-environment#configure_build_environment_gradle_daemon
org.gradle.parallel=true

# AndroidX package structure to make it unambiguous which package your dependency is using pick the one you depend on.
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enable Gradle build cache
org.gradle.caching=true

# JVM Configuration for Java 21
kotlin.jvmTarget=21
org.gradle.configuration-cache=true
